version: '3'
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    restart: always
    depends_on:
      - database

  nginx:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    restart: always
    depends_on:
      - api


  database:
    image: mongo
    ports:
      - '27017:27017'
