version: '3'
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    restart: always
    depends_on:
      - database
  nginx:
    depends_on:
      - api
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "80:80"
      
  database:
    image: mongo
    ports:
      - '27017:27017'
